services:
  server:
    build:
      context: ./packages/server
      dockerfile: Dockerfile
    env_file:
      - ./packages/server/.env
    environment:
      CERT_PATH: /usr/src/app/certs/server.crt
      KEY_PATH: /usr/src/app/certs/server.key
    volumes:
      - ./certs:/usr/src/app/certs
      - ./packages/server/assets/db:/usr/src/app/assets/db
    ports:
      - "3100:3100"
      - "3000:3000"

  client:
    build:
      context: ./packages/client
      dockerfile: Dockerfile
    volumes:
      - ./certs:/usr/src/app/certs
    environment:
      CERT_PATH: /usr/src/app/certs/server.crt
      KEY_PATH: /usr/src/app/certs/server.key
    ports:
      - "8080:8080"
      - "8443:8443"
