services:
  server:
    build:
      context: ./packages/server
      dockerfile: Dockerfile
    env_file:
      - ./packages/server/.env
    volumes:
      - ./packages/server/certs:/usr/src/app/certs
    networks:
      - caddy

  client:
    build:
      context: ./packages/client
      dockerfile: Dockerfile
    networks:
      - caddy

  caddy:
    image: caddy:latest
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
    networks:
      - caddy
    ports:
      - "80:80"
      - "443:443"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
networks:
  caddy:
